flag to optionally consider overrides for gather-and-list as well
Olical/depot pull request #15
Opened 2019-01-15 07:36 UTC by daaku

It seems like `--update` already processes `override-deps`. This new flag allows for the default gather-and-print action to also consider `override-deps` in a similar fashion.

2019-01-20 15:31 UTC, Olical requested changes
Looking good other than an `if` over a `when` (I think?). I'll give it a spin once that's corrected. Thanks for the improvement!

Sorry about the slow response, I was on holiday.

2019-01-20 15:31 UTC, Olical commented on src/depot/outdated.clj
> +                        (if include-overrides overrides))]
This should be a `when`, right?

2019-01-20 19:23 UTC, daaku commented
Not familiar with Github reviews, but just in case it didn't notify you - I updated the code to resolve the `if` -> `when` issue.

2019-01-21 20:12 UTC, Olical approved these changes

2019-01-21 20:27 UTC, merged

2019-01-21 20:35 UTC, Olical commented
Thank you! Released in `v1.6.0`.